#### Universidad del Valle de Guatemala<br>Data Science<br>Laboratorio\#10<br>Grupo\#4

In [1]:
!pip install pyreadstat

Collecting pyreadstat
  Downloading pyreadstat-1.2.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 25.6 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from pyreadstat) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->pyreadstat) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->pyreadstat) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->pyreadstat) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas>=1.2.0->pyreadstat) (1.16.0)
Installing collected packages: pyreadstat
Successfully installed pyreadstat-1.2.4

In [2]:
import pandas as pd
import pyreadstat

archivo_sav_Hogar = 'ENCOVI_Hogar.sav'
archivo_sav_Personas = 'ENCOVI_Personas.sav'

# Utiliza pyreadstat para cargar el archivo .sav
datos_Hogar, metadatos_Hogar = pyreadstat.read_sav(archivo_sav_Hogar)
datos_Personas, metadatos_Personas = pyreadstat.read_sav(archivo_sav_Personas)

In [3]:
datos_Hogar

,REGION,DEPTO,AREA,UPM,NUMHOG,FACTOR,FACTOR3,POBREZA,THOGAR,PPB01,...,P01H10,P01H11,P01H12,P01H13,P01H14,P01H15,P01H16,DIA_ENC,MES_ENC,A_ENC
0,1.0,1.0,1.0,1.0,1.0,525.0,1575.0,3.0,3.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0,8.0,2014.0
1,1.0,1.0,1.0,1.0,2.0,525.0,1575.0,3.0,3.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,8.0,2014.0
2,1.0,1.0,1.0,1.0,3.0,525.0,9450.0,2.0,18.0,2.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,22.0,8.0,2014.0
3,1.0,1.0,1.0,1.0,4.0,525.0,3150.0,2.0,6.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,24.0,8.0,2014.0
4,1.0,1.0,1.0,1.0,5.0,525.0,1575.0,3.0,3.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0,8.0,2014.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11531,8.0,17.0,2.0,833.0,11532.0,305.0,915.0,3.0,3.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,5.0,12.0,2014.0
11532,8.0,17.0,2.0,833.0,11533.0,305.0,3355.0,1.0,11.0,2.0,...,1.0,1.0,2.0,1.0,1.0,2.0,2.0,5.0,12.0,2014.0
11533,8.0,17.0,2.0,833.0,11534.0,305.0,1220.0,2.0,4.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,5.0,12.0,2014.0
11534,8.0,17.0,2.0,833.0,11535.0,305.0,915.0,3.0,3.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,6.0,12.0,2014.0
11535,8.0,17.0,2.0,833.0,11536.0,305.0,1830.0,1.0,6.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,5.0,12.0,2014.0

In [7]:
df_Hogar = pd.DataFrame(datos_Hogar)

In [5]:
datos_Personas

,REGION,DEPTO,AREA,UPM,NUMHOG,FACTOR,POBREZA,THOGAR,ID,PPA02,...,P11A10A,P11A10B,P11B01A,P11B01B,P11B02A,P11B02B,P11B03A,P11B03B,P11B04A,P11B04B
0,1.0,1.0,1.0,1.0,1.0,525.0,3.0,3.0,1.0,1.0,...,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN
1,1.0,1.0,1.0,1.0,1.0,525.0,3.0,3.0,2.0,2.0,...,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN
2,1.0,1.0,1.0,1.0,1.0,525.0,3.0,3.0,3.0,2.0,...,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN
3,1.0,1.0,1.0,1.0,2.0,525.0,3.0,3.0,1.0,2.0,...,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN
4,1.0,1.0,1.0,1.0,2.0,525.0,3.0,3.0,2.0,1.0,...,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54817,8.0,17.0,2.0,833.0,11536.0,305.0,1.0,6.0,2.0,2.0,...,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN
54818,8.0,17.0,2.0,833.0,11536.0,305.0,1.0,6.0,3.0,1.0,...,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN
54819,8.0,17.0,2.0,833.0,11536.0,305.0,1.0,6.0,4.0,2.0,...,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN
54820,8.0,17.0,2.0,833.0,11536.0,305.0,1.0,6.0,5.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54821,8.0,17.0,2.0,833.0,11536.0,305.0,1.0,6.0,6.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df_Personas = pd.DataFrame(datos_Personas)